# Generated by Django 5.0.7 on 2024-08-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.TextField(default=0),
        ),
    ]
